theme = "native"
icons = "awesome"

[[block]]
block = "kdeconnect"

[[block]]
block = "weather"
format = "{temp}"
service = {name = "openweathermap", api_key = "9eb1aeef2556212c5471df63111e76b1",place = "Saint Petersburg, RU",units = "metric"}

[[block]]
block = "custom"
command = "spt playback --format"
on_click = "spt playback --toggle"
interval = 3

[[block]]
block = "temperature"
format = "{average}"
collapsed = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used;M}"

[[block]]
block = "networkmanager"
device_format = "{ap}"

[[block]]
block = "time"
interval = 5
format = "%d/%m %R"

